name: rl_proj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - stable-baselines3==2.3.0
      - sb3-plus==0.1.3
      - git+https://github.com/chiral-carbon/PynkTromboneGymnasium.git@master